python get_thalamus_volumes.py 1003 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1023 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1042 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1065 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1071 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1076 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1094 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1107 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1119 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1125 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1131 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1152 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1155 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1161 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1165 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1167 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1198 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1218 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1225 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1235 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1240 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1241 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1248 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1257 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1301 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1318 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1326 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1358 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1360 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1376 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1382 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1417 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1442 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1479 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1508 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 1527 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 2006 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 2025 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 2075 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 2112 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 2178 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
python get_thalamus_volumes.py 2195 /mnt/h/3Tpioneer_bids /mnt/h/srs-9/longitudinal
